# These are supported funding model platforms

github: wuseman
patreon: wuseman
open_collective: wuseman
ko_fi: wuseman
tidelift: wuseman
community_bridge: wuseman
liberapay: wuseman
issuehunt: wuseman
otechie: wuseman
lfx_crowdfunding: wuseman
custom: wuseman
